Fix 5e.tools incompatibilities
haswellr/CritterDB pull request #111
Opened 2023-02-10 16:10 UTC by hogart

Addresses #89

The export is still not ideal, but most of the fields are transferred properly, and the creatures are actually visible in 5.tools' homebrew editor.

Also adds minor non-breaking feature to allow the server to run on different port.

2023-02-15 16:40 UTC, haswellr commented on server/controllers/users.js
> +    return;
I think these changes accidentally slipped in. Otherwise looks good.

2023-02-15 16:41 UTC, haswellr requested changes
If you remove the change to the welcome email, I'll push and deploy these. Thanks for helping out!

2023-02-15 17:15 UTC, hogart commented
> If you remove the change to the welcome email, I'll push and deploy these. Thanks for helping out!

My bad! Fixed. 
Please let me know once it's deployed, I need to port quite a bestiary:)

2023-02-16 04:03 UTC, haswellr approved these changes

2023-02-16 04:03 UTC, merged

2023-02-16 05:57 UTC, haswellr commented
I had to put in a quick change because CritterDB is terribly old and the build process doesn't support the spread operator, but it is deployed now!

2023-02-16 08:20 UTC, hogart commented
Thank you very much for the great tool!